### ISSUE TITLE
match css selectors in scripts in the html

### ISSUE THREAD

**Issue by jonatanpedersen** [jonatanpedersen/css-bingo#2]
given:

``` css
.foo { color: #c00; }
.foo--bar { color: #0c0; }
```

and

``` html
<html>
	<body>
		<div class="foo">foo</div>
		<script>
			const fooElement = document.querySelector('.foo');
			fooElement.classList.add("foo--bar");
		</script>
	</body>
</html>
```

it should match `.foo` and `.foo--bar`
